version: '3.9'

services:
  wik-dps-tp03:
    build:
      context: .
      dockerfile: multi-stage.dockerfile
    deploy:
      replicas: 4
    restart: always
    environment:
      - PORT=8080
    networks:
      - front-network

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - wik-dps-tp03
    networks:
      - front-network


networks:
  front-network:
    driver: bridge
